# Use official Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
  && apt-get install -y build-essential libpq-dev netcat-openbsd gcc curl \
  && apt-get clean

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY src/ .

# Collect static files
RUN mkdir -p /app/staticfiles

# Expose port
EXPOSE 8000

# Start Gunicorn
CMD ["gunicorn", "home.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
