name: Scheduled Stripe Subscription Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,12 * * *'       # every day at 1 AM and 12 PM UTC
    - cron: '0 4 1 * *'          # monthly cleanup on the 1st at 4 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      DJANGO_DEBUG: 1
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.RDS_DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Django secret key
        run: |
          echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Migrate database
        working-directory: ./src
        run: |
          python manage.py migrate

      - name: Sync active Stripe subscriptions (daily)
        if: github.event.schedule != '0 4 1 * *'
        working-directory: ./src
        run: |
          python manage.py sync_user_subs --day-start 0 --day-end 1

      - name: Clear dangling Stripe subscriptions (monthly)
        if: github.event.schedule == '0 4 1 * *'
        working-directory: ./src
        run: |
          python manage.py sync_user_subs --clear-dangling
